# @file: Configurações da classe Context de teste
# @author: @douglaspands
# @date: 2018-09-23
# @version: 1.0.0
---
# Pasta limite de busca dos modulos (recursividade)
folderLimit: main
# Stack
stack:
  # Ordem do arquivo 
  fileOrder: 3