"""
Objeto Funcionario
"""
type Funcionario {
    "ID do Funcionario"
    _id: ID!
    "Nome do funcionario"
    nome: String
    "Sobrenome do funcionario"
    sobrenome: String
    "Cidade onde o funcionario mora"
    cidade: String
    "Estado onde o funcionario mora"
    estado: String
    "Telefone do funcionario"
    telefone: String
    "Email do funcionario"
    email: String
}
"""
Objeto de inclusão do Funcionario
"""
input inputFuncionario {
    "Nome do funcionario"
    nome: String
    "Sobrenome do funcionario"
    sobrenome: String
    "Cidade onde o funcionario mora"
    cidade: String
    "Estado onde o funcionario mora"
    estado: String
    "Telefone do funcionario"
    telefone: String
    "Email do funcionario"
    email: String
}
"""
Funções de consulta
"""
type Query {
    """
    Consultar funcionario pelo ID
    """
    obterFuncionario(
        "ID do Funcionario"
        _id: ID!
    ): Funcionario
    """
    Pesquisar funcionario
    - Todos os parametros solicitados são opcionais, preenchendo apenas os campos que deseja pequisar.
    """
    pesquisarFuncionarios(
        "Nome do funcionario (opcional)"
        nome: String
        "Sobrenome do funcionario (opcional)"
        sobrenome: String
        "Cidade onde o funcionario mora (opcional)"
        cidade: String
        "Estado onde o funcionario mora (opcional)"
        estado: String
        "Telefone do funcionario (opcional)"
        telefone: String
        "Email do funcionario (opcional)"
        email: String
    ): [Funcionario]
}
"""
Funções de persistencia
"""
type Mutation {
    """
    Criar funcionario
    """
    criarFuncionario(
        "Dados do Funcionario"
        input: inputFuncionario
    ): Funcionario
    """
    Atualizar funcionario pelo ID
    """
    atualizarFuncionario(
        "ID do Funcionario (Obrigatorio)"
        _id: ID!
        "Nome do funcionario"
        nome: String
        "Sobrenome do funcionario"
        sobrenome: String
        "Cidade onde o funcionario mora"
        cidade: String
        "Estado onde o funcionario mora"
        estado: String
        "Telefone do funcionario"
        telefone: String
        "Email do funcionario"
        email: String
    ): Funcionario
    """
    Remover funcionario"
    """
    removerFuncionario(
        "ID do Funcionario"
        _id: ID!
    ): String
}
