# Objeto de inclusao de funcionario
input incluirFuncionario {
    # Nome do funcionario
    nome: String
    # Sobrenome do funcionario
    sobrenome: String
    # Cidade onde o funcionario mora
    cidade: String
    # Estado onde o funcionario mora
    estado: String
    # Telefone do funcionario
    telefone: String
    # Email do funcionario
    email: String
}
# Objeto Funcionario
type Funcionario {
    # ID do Funcionario
    _id: ID!
    # Nome do funcionario
    nome: String
    # Sobrenome do funcionario
    sobrenome: String
    # Cidade onde o funcionario mora
    cidade: String
    # Estado onde o funcionario mora
    estado: String
    # Telefone do funcionario
    telefone: String
    # Email do funcionario
    email: String
}
# Funções de consulta
type Query {
    # Consultar funcionario pelo ID
    obterFuncionario(_id: ID!): Funcionario
    # Listar funcionarios
    listarFuncionarios: [Funcionario]
    # Pesquisar funcionario
    pesquisarFuncionarios(nome: String, sobrenome: String, cidade: String, estado: String, telefone: String, empresa: String): [Funcionario]
}
type Mutation {
    # Criar funcionario
    criarFuncionario(input: incluirFuncionario): Funcionario
    # Atualizar funcionario pelo ID
    atualizarFuncionario(_id: ID!, nome: String, sobrenome: String, cidade: String, estado: String, telefone: String, empresa: String): String
    # Remover funcionario
    removerFuncionario(_id: ID!): String
}
