version: '3.1'
services:
    api-core-js:
        build:
            dockerfile: ./Dockerfile
            context: ./src
        image: api-core-js:latest
        container_name: api-core-app
        volumes: 
            - "./logs:/var/www/logs"
        ports:
            - "3000:3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"
    mongodb:
        image: mongo:latest
        container_name: api-core-db
        volumes: 
            - "./data:/data/db"
        networks: 
            - production-network
        ports:
            - "27017:27017"
networks: 
    production-network:
        driver: bridge