# file: stack-dev.yaml 
# description: Criar container da aplicação (develop). 
version: '3.5'
services:
    mongo:
        image: mongo:4.0.1
        container_name: apicore-mongo
        volumes: 
            - mongo-data:/data/db
        ports:
            - 27017:27017
        networks: 
            - develop-network
    redis:
        image: redis:4.0.11-alpine
        container_name: apicore-redis
        ports:
            - 6379:6379
        networks: 
            - develop-network
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        container_name: apicore-elastic
        volumes:
            - es-data:/usr/share/elasticsearch/data
        environment: 
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - develop-network
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.0
        container_name: apicore-kibana
        environment: 
            - ELASTICSEARCH_URL:elasticsearch:9200
        ports:
            - 5601:5601
        networks:
            - develop-network
        depends_on:
            - elasticsearch
networks: 
    develop-network:
        driver: bridge
volumes:
    # /var/lib/docker/volumes/
    mongo-data:
        driver: local
    es-data:
        driver: local
