# file: stack-full-dev.yaml 
# description: Criar container da aplicação toda. 
version: '3.5'
services:
    apicore:
        build:
            dockerfile: ./Dockerfile
            context: ./src
        image: douglaspands/apicorejs:2.9.0
        container_name: apicore-app
        environment:
            - MONGO_URL=mongo:27017
            - REDIS_URL=redis:6379
            - LOG_LEVEL=info
            - PORT=3000
            - NODE_ENV=development # development : GraphQL IDE
        volumes: 
            - app-data:/var/www/logs
        ports:
            - 3000:3000
            - 3001:3001
        networks:
            - production-network
        depends_on:
            - mongo
            - redis
    mongo:
        image: mongo:4.0.1
        container_name: apicore-mongo
        volumes: 
            - mongo-data:/data/db
        ports:
            - 27017:27017
        networks: 
            - production-network
    redis:
        image: redis:4.0.11-alpine
        container_name: apicore-redis
        ports:
            - 6379:6379
        networks: 
            - production-network
networks: 
    production-network:
        driver: bridge
volumes:
    app-data: 
        driver: local
    mongo-data:
        driver: local
