# file: stack-dev.yaml 
# description: Criar container da aplicação (desenvolvimento).
# Disponibiliza a interface GraphiQL e todos acessos aos servidores.
version: '3.5'
services:
    core-api-js:
        build:
            dockerfile: ./Dockerfile
            context: ./src
        image: douglaspands/core-api-js:2.6.2
        container_name: apicore-app
        environment:
            - MONGO=mongo-db:27017
            - REDIS_CACHE=redis-cache:6379
            - PORT=3000
            - NODE_ENV=development
        volumes: 
            - "./logs:/var/www/logs"
        ports:
            - "3000:3000"
            - "3001:3001"
        networks:
            - develop-network
        depends_on:
            - "mongo-db"
            - "redis-cache"
    mongo-db:
        image: mongo:4.0.1
        container_name: apicore-db
        volumes: 
            - "./data:/data/db"
        networks: 
            - develop-network
        ports:
            - "27017:27017"
    redis-cache:
        image: redis:4.0.11-alpine
        container_name: apicore-cache
        networks: 
            - develop-network
        ports:
            - "6379:6379"
networks: 
    develop-network:
        driver: bridge