# file: stack-prd.yaml 
# description: Criar container da aplicação (producao). 
version: '3.5'
services:
    api-core-js:
        build:
            dockerfile: ./Dockerfile
            context: ./src
        image: douglaspands/api-core-js:2.7.1
        container_name: apicore-app
        environment:
            - MONGO_URL=mongo:27017
            - REDIS_URL=redis:6379
            - ELASTIC_URL=elasticsearch:9200
            - LOG_LEVEL=info
            - PORT=3000
        volumes: 
            - "./logs:/var/www/logs"
        ports:
            - "3000:3000"
            - "3001:3001"
        networks:
            - production-network
        depends_on:
            - "mongo"
            - "redis"
            - "elasticsearch"
    mongo:
        image: mongo:4.0.1
        container_name: apicore-mongo
        volumes: 
            - "./mongo_data:/data/db"
        ports:
            - "27017:27017"
        networks: 
            - production-network
    redis:
        image: redis:4.0.11-alpine
        container_name: apicore-redis
        ports:
            - "6379:6379"
        networks: 
            - production-network
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        container_name: apicore-elastic
        environment: 
            - "discovery.type=single-node"
        volumes:
            - "./elastic_data:/usr/share/elasticsearch/data"
        ports:
            - "9200:9200"
        networks:
            - production-network
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.0
        container_name: apicore-kibana
        environment: 
            - "ELASTICSEARCH_URL:elasticsearch:9200"
        ports:
            - "5601:5601"
        networks:
            - production-network
        depends_on:
            - "elasticsearch"
networks: 
    production-network:
        driver: bridge