# file: stack-dev.yaml 
# description: Executar uma instancias de banco: mongo, redis e elaticsearch/kibana.
version: '3.5'
services:
    mongodb:
        image: mongo:4.0.1
        container_name: apicore-mongo
        volumes: 
            - mongo-data:/data/db
        ports: 
            - 27017:27017
    redis:
        image: redis:4.0.11-alpine
        container_name: apicore-redis
        command: ["redis-server", "--appendonly", "yes"]
        volumes: 
            - redis-data:/data
        ports: 
            - 6379:6379
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        container_name: apicore-elastic
        environment: 
            - discovery.type=single-node
        volumes: 
            - es-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200 
            - 9300:9300
    kibana:
        image: docker.elastic.co/kibana/kibana:6.4.0
        container_name: apicore-kibana
        ports: 
            - 5601:5601
        depends_on: 
            - elasticsearch      
volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
  es-data:
    driver: local
