input incluirUsuario {
    nome: String
    sobrenome: String
    idade: Int
    cidade: String
    estado: String
    cep: String
    telefone: String
}
type Usuario {
    _id: ID!
    nome: String
    sobrenome: String
    idade: Int
    cidade: String
    estado: String
    cep: String
    telefone: String
}
type Query {
    obterUsuario(_id: ID!): Usuario
    listarUsuarios: [Usuario]
    pesquisarUsuarios(nome: String, sobrenome: String, idade: Int, cidade: String, estado: String, cep: String, telefone: String): [Usuario]
}
type Mutation {
    criarUsuario(input: incluirUsuario): Usuario
    atualizarUsuario(_id: ID!, nome: String, sobrenome: String, idade: Int, cidade: String, estado: String, cep: String, telefone: String): String
    removerUsuario(_id: ID!): String
}
