# @file: Configurações para pesquisa das controllers
# @author: @douglaspands
# @date: 2018-09-21
# @version: 1.1.20180926
---
# Fonte onde esta o controller da API
file: index.js
# Expressão regular para obter informações da rota
file_type: "^(.+)([\\\\/])route.(yaml|yml)$"
# Verbos HTTP valido
methods:
  - get
  - put
  - post
  - patch
  - delete
  - options
